### ISSUE TITLE
Store data on local computer

### ISSUE THREAD

**Issue by joshperrin** [wojtkowiak/meteor-desktop#100]
Hey there,

I've been looking through all your documentation. And if I'm understanding correctly this only builds the Meteor client, not the server, correct?

Is there a way using this package to connect to a remote a server for a few things, but store most of the data locally?

thanks!

**Comment by wojtkowiak** [comment]
Hello,

yes, this is a client only integration. 

> Is there a way using this package to connect to a remote a server for a few things, but store most of the data locally?

Well you can do that in many ways. Some people are using https://github.com/GroundMeteor/db for that afaik. You can use localStorage or indexedDB (indexedDB will be supported in 1.0) or you can just write you own storage mechanism on the desktop side. The problem is that you have to dump your collections and then restore them at next app startup but it's definitely doable.

Bundling mongo and meteor server is in the plan after first 1.0 release.

**Comment by KoenLav** [comment]
@wojtkowiak do you have a planned release date for 1.0 (or just the new client storage facilities)? 

We're running into some issues with localstorage being unavailable sometimes.

Is there any branch/defined issue we could work on to speed up the release of these functionalities?

**Comment by KoenLav** [comment]
@wojtkowiak we tried using LocalForage and also created a module for the ElectronSettings package.

Can share the code if required, or discuss which implementations could/should be considered :)
