### ISSUE TITLE
Where do I access the app 'ready' callback

### ISSUE THREAD

**Issue by stocksp** [wojtkowiak/meteor-desktop#13]
I'm confused by the boilerplate code.
I'm looking for an app.on('ready') callback where I can
setup the main window and menu.
Specifically I'm trying to enable copy and past as shown here
https://pracucci.com/atom-electron-enable-copy-and-paste.html
and I need to control the size the application opens at (much larger than it is).

**Comment by stocksp** [comment]
oh!  rtfm ...  settings.json supports width and height on the window object. and I was able to use 'electron-context-menu' to get the copy/paste context menu working.

**Comment by wojtkowiak** [comment]
The current documentation is messy a little bit right now.
Glad that you've worked it out.
When it comes to the `ready` event everything that happens in the constructors of modules and `desktop.js` is triggered inside a `ready` handler.
I will leave this open - because I will add some note about it in the docs :smile:

**Comment by wojtkowiak** [comment]
Added https://github.com/wojtkowiak/meteor-desktop#where-is-my-apponready :)
