### ISSUE TITLE
build-installer loses menu bar

### ISSUE THREAD

**Issue by stocksp** [wojtkowiak/meteor-desktop#17]
meteor-desktop run produces a complete menu bar (Electron Edit View ....)
build-installer only has a quit option in the produced dmg.
This happens with a simple default Meteor 'todo' project.
Mac OS
Is the menu bar I'm seeing with 'run' just part of the dev environment?
Should I be constructing my own menu bar?

P:)

**Comment by wojtkowiak** [comment]
This is intentional. Because normally the produced app is run by the `electron` command line it is wrapped in a simple app that provides this menu. When you run a packaged version this menu will not appear.
More here: https://github.com/electron-userland/electron-packager/issues/131#issuecomment-139670055

If you want to replicate it, simply copy it from the default electron app here:
https://github.com/electron/electron/blob/master/default_app/main.js#L50

**Comment by stocksp** [comment]
Excellent .. works like a charm!
Thanks so much for your patience!
