### ISSUE TITLE
How to create loading screen when meteor desktop app is loading

### ISSUE THREAD

**Issue by lokiribeiro** [wojtkowiak/meteor-desktop#176]
Hi,

How do I edit desktop.js in a way where I can include a loading screen for when the meteor desktop app is loading its content from a meteor server.

Right now what happens when I run my desktop app is:
1.splash screen shows
2. my app shows but with no centent (empty)
3. after 7-9 seconds before the content of the page is rendered

I wanted to add a loading screen to fill in the empty 7-9 seconds  loading gap.

**Comment by wojtkowiak** [comment]
Hey,

this is weird, splashscreen hides when Chrome finishes loading the app. Is it a big app? 7-9 seconds to process JS seems very long.
You can switch to hiding splashscreen when Meteor announces its readiness by setting `showWindowOnStartupDidComplete`  to `true` in `settings.json`. Check it out.
Otherwise you are free to hook into any event from [eventsbus](https://github.com/wojtkowiak/meteor-desktop/blob/master/README.md#eventsbus) and display another window with a loading screen.
If you need any other events added let me know.

**Comment by lokiribeiro** [comment]
Hi,

I was able to make it work by setting showWindowOnStartupDidComplete to true.

Thanks :)

**Comment by wojtkowiak** [comment]
Great :)
