### ISSUE TITLE
Access to webFrame or other renderer APIs

### ISSUE THREAD

**Issue by lunafi-evan** [wojtkowiak/meteor-desktop#184]
I'm unable to access [webFrame API](https://github.com/electron/electron/blob/v2.0.4/docs/api/web-frame.md) on the client, even though it's running in the renderer process and should be available. Is there a way to access renderer-specific APIs? I need to embed an iframe and the default Content Security Policy doesn't allow it, I need access to `webFrame.registerURLSchemeAsBypassingCSP(scheme)` in order to modify the CSP in the renderer process.

**Comment by wojtkowiak** [comment]
This is not possible at the moment as the render has `nodeIntegration: false` for both security and meteor compatibility reasons.
Meaning you can not use any Electron API in renderer directly. The webFrame api is a problematic one because you can use from the main process.
I will add a possibility to expose it when configured, so it will be accessible as `Desktop.electron.webFrame` - I will try to push that into upcoming `1.6.0`.

**Comment by lunafi-evan** [comment]
this was included in `1.6.0`, thanks1
