### ISSUE TITLE
cannot find mongodb server

### ISSUE THREAD

**Issue by lorenzogm** [wojtkowiak/meteor-desktop#19]
Hi @wojtkowiak 

I got new issues distributing the windows installer:

If I run `npm run desktop build-installer` when `meteor --mobile="127.0.0.1:3000` everything works fine but the installed app only works if meteor is running. If I install it in another computer, something related with DB (like users) doesn't work. And I tried to find the mongodb server in localhost:PORT (the port in the log files at %appdata%) and it doesn't exists.

On the other hand, if I try `npm run desktop build-installer --build-meteor --production` (It looks like production is already set by `--build-installer`) to see if this creates a mongodb server with the DB. However, I get this log:

```
> npm run desktop build-installer --build-meteor --production

> test@ desktop C:\Users\tests\src
> meteor-desktop "build-installer"

package/build-installer implies setting --production, setting it for you
!expecting a meteor project running on port 3000!

INFO  index:  initializing
INFO  electronApp:  scaffolding
VERBOSE  desktop:  checking .desktop existence
VERBOSE  meteorApp:  updating .meteor/.gitignore
VERBOSE  meteorApp:  desktopHCP is enabled, checking for required packages
VERBOSE  electronAppScaffold:  clearing desktop-build
VERBOSE  electronAppScaffold:  creating C:\Users\tests\src\.meteor\desktop-build\app
VERBOSE  electronAppScaffold:  copying skeleton app
VERBOSE  electronAppScaffold:  writing package.json
VERBOSE  electronApp:  updating package.json fields
DEBUG  electronApp:  writing updated package.json
INFO  electronApp:  updating list of package.json's dependencies
DEBUG  electronApp:  merging settings.json[dependencies]
DEBUG  electronApp:  merging settings.json[plugins]
DEBUG  electronApp:  merging dependencies from modules
DEBUG  electronApp:  writing updated package.json
VERBOSE  electronApp:  calculating compatibility version
DEBUG  electronApp:  meteor-desktop compatibility version is  0.1
DEBUG  electronApp:  .desktop compatibility version is  2
INFO  electronApp:  installing dependencies
DEBUG  electronApp:  running npm prune to wipe unneeded dependencies
VERBOSE  electronApp:  executing npm install
WARN  electronApp:  native modules rebuild is turned off, be sure to turn it on if you added any native node modules
INFO  electronApp:  packing skeleton app and node_modules to asar archive
DEBUG  electronApp:  moving node_modules
DEBUG  electronApp:  packing
DEBUG  electronApp:  moving node_modules back
DEBUG  electronApp:  deleting source files
VERBOSE  electronApp:  copying .desktop to temporary location
DEBUG  electronApp:  updating settings.json fields
INFO  desktop:  calculating hash version from .desktop contents
INFO  electronApp:  excluding files from packing
INFO  electronApp:  transpiling and uglifying
INFO  electronApp:  packing .desktop to asar
VERBOSE  electronApp:  clearing temporary .desktop
INFO  meteorApp:  checking for any mobile platform
INFO  meteorApp:  building meteor app
DEBUG  meteorApp:  clearing build dir
INFO  meteorApp:  acquiring index.html
ERROR  meteorApp:  error while trying to download index.html for web.cordova, be sure that you are running a mobile target or with --mobile-server:  { [FetchError: request to http://127.0.0.1:3000/__cordova/index.html failed, reason: connect ECONNREFUSED 127.0.0.1:3000]
  name: 'FetchError',
  message: 'request to http://127.0.0.1:3000/__cordova/index.html failed, reason: connect ECONNREFUSED 127.0.0.1:3000',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "desktop" "build-installer" "--build-meteor" "--production"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! test@ desktop: `meteor-desktop "build-installer"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@ desktop script 'meteor-desktop "build-installer"'.
npm ERR! This is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor-desktop "build-installer"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tests\src\npm-debug.log
```

So, how can I get a mongodb instance working without meteor running?

Thanks!

**Comment by wojtkowiak** [comment]
Hey @lorenzogm,

I see two problems here.

First: you have a mistake  in your console syntax:

wrong: `npm run desktop build-installer --build-meteor --production`
good: ``npm run desktop build-installer -- --build-meteor --production`
notice the ` -- ` delimiter.
Without the delimiter options are passed to `npm` instead of `meteor-desktop` so `--build-meteor` does nothing.

Second:
> So, how can I get a mongodb instance working without meteor running?

You can't. The is a desktop client, so the mongo nor meteor is not builtin.
You need to point your Meteor app to your server, so assuming you have one machine with ip for example `192.168.0.1` and running a meteor there you need to build installer with the correct ddp url parameter. So in order for the app to work you need to build it with:

`npm run desktop build-installer -- http://192.168.0.1:3000 --build-meteor`

This way when you install it on another machine with ip for instance `192.168.0.2` it will connect to the correct ip where your meteor server is.

Hope I've helped :wink:

**Comment by wojtkowiak** [comment]
I will release a `0.1.3` in a few minutes that will try to automatically warn you in case of missing delimiter when invoking `npm run` with args.

**Comment by lorenzogm** [comment]
Thank you for your quick response @wojtkowiak 

Yes, a problem with the delimiter again, sorry :(

However, is there any way to integrate the mongodb server in the installer?

**Comment by wojtkowiak** [comment]
No problem @lorenzogm :)
Well, you are rather thinking of embedding the whole meteor server, right? Because mongodb alone is not something you can connect to through DDP.
This package https://github.com/arboleya/electrify does what you need but it is not maintained anymore I guess.

When it comes to this solution it would be hard but not impossible. I depends on your needs, maybe you could just use a sqlite database in the `.desktop` and push data there and back again over ipc? Or you could even run your own ddp server on the desktop side and connect to it from the meteor app. The latter I am actually planning to experiment with past `1.0.0`.

**Comment by lorenzogm** [comment]
Thanks @wojtkowiak 

Yes, I need the whole app packaged to be used without any external dependency. I tried that package and another one more updated: (https://github.com/Unforgiven-wanda/electrify-updated-test). But I couldn't make it works. And, the functionalities for `meteor-desktop` to build, package and create the installer are great.

Do you think is it possible to include mongodb, like in `electrify`, in this project? I could contribute very actively to that feature, but I don't have any experience with electron. If you could point me in the right direction in this process I could try to achieve it ASAP.

Please, let me know your thoughts :)

**Comment by wojtkowiak** [comment]
Ok, so basically doing something similar to whats electrify is doing is something I really wanted to avoid at all costs :wink:
By design this was intended to be a **client** only.

However... why not... we can try, if you feel brave enough :wink: 

> Do you think is it possible to include mongodb, like in electrify, in this project?

Yes, but if you really want to  do it, lets sketch a plan.

1. Pack Mongo inside a npm package.
2. Add build plugins API to meteor-desktop.
3. Make a build plugin, that will do `meteor build` and will take the built app, preferably pack it to asar and add it as asset.
4. Make a plugin that will run Mongo and meteor server while the desktop app is starting.

Very roughly that should be it, but I can not promise that everything is actually feasible from this list.

So here is some guidance for task 1.
Here is how meteor bundle is being made and how mongo is packed inside -> https://github.com/meteor/meteor/blob/devel/scripts/generate-dev-bundle.sh#L28
I would do a npm package that downloads mongo binaries upon install and contains small wrapper for specifying some basic options like where the db should be stored and a simple runner. I would check for example how electron package is downloading its binaries and use this way as I have never done it before.
I would not depend on copying mongo from meteor's dev bundle like electrify does, but I guess most of the code here https://github.com/arboleya/electrify/blob/master/lib/plugins/mongodb.js can be used later to spawn it.

Of course it's up to you how want to approach this. If needed I can later prepare point 2 & 3.

**Comment by wojtkowiak** [comment]
Oh I forgot we also need different node version for running meteor. 

So... seems that I would need some more time to think about it. Initially I was against it, but on a second thought, maybe for the start, you can use electrify's code and copy node and mongo from meteor's dev bundle. 

So do a npm package that finds meteor dev bundle by version and copies mongo and node binaries.
Let me know when would you need the build api to be ready so that you could hook that up to the `meteor-desktop` build process.

**Comment by lorenzogm** [comment]
Hi @wojtkowiak Thank you for your answers.

Finally, my app is working with electrify. It's a very useful project, it's just needs some minor changes because it's out of date. Therefore, I'm not in a hurry to include something like electrify in meteor-desktop :)

Maybe it makes sense to integrate the code of electrify to keep everything together and up to date, or maybe to keep both projects split.
