### ISSUE TITLE
problems with meteor-desktop-bundler on windows

### ISSUE THREAD

**Issue by smooth-operator** [wojtkowiak/meteor-desktop#29]
Hello,
After adding meteor desktop on macOS, which works and builds fine for both macOS and windows, i can't start meteor on windows for normal development with error:

Errors prevented startup:
   While loading plugin `meteor-desktop-bundler` from package `omega:meteor-desktop-bundler`:
   module.js:325:15: Cannot find module 'lodash/cloneDeep'

I tried running npm install lodash and npm install lodash.cloneDeep and it didn't help.
Any ideas?

Thanks,
Catalin

**Comment by mrzafod** [comment]
Hi, 
The same on Win10, but works fine on Ubuntu 16.
Thanks

**Comment by wojtkowiak** [comment]
Hey @smooth-operator and @mrzafod,

I need some more details like Meteor version, meteor-desktop version, windows version.
Does this occur when running meteor without `--mobile-server`? Was `meteor-desktop` installed with `meteor npm` or plain `npm`?

**Comment by smooth-operator** [comment]
Hi,
I'm trying to run it on Windows 10 with Meteor 1.4.2.3 and meteor-desktop 0.2.1. I installed meteor-desktop using plain npm. I get that error with or without --mobile-server. I just tried installing lodash with meteor npm as well and i get the same error.
Thanks

**Comment by tzapu** [comment]
some added details to @smooth-operator 's account, for one of the scenarios we tried:
- can't add a mobile platform on windows it seems, meteor says it s not supported
- we installed meteor-desktop and ios platform intially on macOS and the project is worked upon by me in collaboration with @smooth-operator 
- on macOS , all is good
- on windows we can no longer start the meteor project to work on it normally, without any meteor desktop features because of the error in the scaffold-ed package mentioned above
Hopefully this helps explain what is happening some more.

**Comment by wojtkowiak** [comment]
@tzapu thanks for kind words, glad that this helps people build great software with Meteor & Electron :wink:

Sorry for some delay with checking this but I am currently slowed down a little bit because of being ill.

So I have reproduced it. Seems that I was using a local cached copy of bundler at `0.2.1` and that is why I did not encounter it. It seems that meteor actually messed up the package and it was published in an unknown, erroneous state... https://github.com/meteor/meteor/issues/8113

I should have a fix withing few hours.

**Comment by wojtkowiak** [comment]
Is this working for you now?

**Comment by tzapu** [comment]
hi, sorry for the long delay, was away most of last week, we ll try it on tomorrow, thank you very much

**Comment by smooth-operator** [comment]
Hi,  sorry for the delay, as @tzapu said we were away for most of the week. So far on windows the problem seems to be fixed, i can run meteor as usual. As soon as we'll test the build on macOS i'll close the issue. Thanks for a great tool and for the fast response.

**Comment by smooth-operator** [comment]
Just checked, everything works. Thanks.
