### ISSUE TITLE
Unable to run devtron

### ISSUE THREAD

**Issue by Ajaay** [wojtkowiak/meteor-desktop#46]
Im probably missing something obvious, but I'm unable to get devtron to run in the console.

I've just fired up meteor-desktop for the first time following the quick start guide.

When I enter require('devtron').install() into the console I get:

Uncaught Error: Cannot find module 'devtron'(…)

I can see the devtron module under the desktop-build\node_modules directory. Is there anywhere else I should be looking?

Thanks

**Comment by calebl** [comment]
I ran into this same problem. It's not documented, but I had to run `Desktop.devtron.install()` from the developer console for the electron app before I could get it to work.

**Comment by wojtkowiak** [comment]
That is weird.
I have removed the activation of it intentionally here: https://github.com/wojtkowiak/meteor-desktop/commit/9f5c335d15b4a01dcbbe77daf42315d9364b3bdb
because `electron-debug` was doing it anyway: https://github.com/sindresorhus/electron-debug#activates-devtron. But it seems that for some reason it sometimes fails...
I will add it back in `0.3.0` that will be released in few days - stay tuned.

**Comment by wojtkowiak** [comment]
`0.3.0` released - let me know if this is now fixed.

**Comment by Ajaay** [comment]
Yes this is now fixed - thanks!
