### ISSUE TITLE
Paypal donate link?

### ISSUE THREAD

**Issue by ethanwillis** [wojtkowiak/meteor-desktop#57]
Hey Man, really appreciate your work. It's really good and it's been of major use to me. Do you have a paypal donation link or something similar?

**Comment by wojtkowiak** [comment]
Hey,
I'm really flattered but to be honest I have never considered that. I need to check how to make that Donate button because I do not know anything about it 🙂 I will add it over the weekend if standard paypal account allows that. I will, of course, list your name in the new Supporters section in the readme if you do not mind 😄

**Comment by ethanwillis** [comment]
@wojtkowiak Sounds good to me! This evening I was looking for a postgres npm package and saw a donate link on their NPM page https://www.npmjs.com/package/pg-promise They use something called "Pledgie" this maybe might be a good fit for you.

**Comment by wojtkowiak** [comment]
Yeah, thanks for this info, this `Pledgie` seems good and transparent 😄 So I will add the link tomorrow to readme. I have already signed a campaign there: https://pledgie.com/campaigns/33341

**Comment by wojtkowiak** [comment]
The link is here https://github.com/wojtkowiak/meteor-desktop#contribution
Feel fry to donate :) Thanks a ton for this initiative.
