### ISSUE TITLE
make meteor-desktop-toaster plugin

### ISSUE THREAD

**Issue by wojtkowiak** [wojtkowiak/meteor-desktop#6]
Wrap `electron-toaster` into a plugin so it could be used directly on the desktop side instead of calling it from the `renderer` process.
Add an example - showing notification about HCP update being applied.

**Comment by tzapu** [comment]
hi, trying to do the same with icon badges, but I am very very new at all this so please excuse any noob stuff.
so far got them working as a module for os x, but for windows i m kind of hitting a brick wall as it seems i need to get access to the window and draw an icon and so on.
This pretty much made me realise I don t understand clearly how your skeleton is structured from the point of view of main process and renderer process. 
I assume that whatever s in meteor is the implicit renderer and that modules run in the main process, but couldn't really find any clear distinction in the docs (and being very new at this, it might have been there, but not clear enough for me to understand).
Also I couldn t find a way to get a reference to the main window from a module.
Could you ping me in the right direction to understand more on how all this is supposed to work together?
The plan for now is to make it work as  a module then to try and turn it into a plugin, so if you are ok with it, i might open more issues related to guidance on this.

P.S. my current thrain of thought is that since the module runs in the main process, i need to use some plugin to render an image (maybe some npm lib) with the badge and just use that instated of document canvas functions I don t have access to on the main process side. a confirmation if i m on the right track would be marvelous :D
thanks again

**Comment by wojtkowiak** [comment]
Task moved to Taiga.

**Comment by tzapu** [comment]
in essence meteor-desktop-system-notifications does notifications and dock badges until this is ready

is taiga public?

**Comment by wojtkowiak** [comment]
@tzapu to be honest I will probably not make it as I like your plugin more than https://github.com/s-a/electron-toaster ;)
Now I am considering adding an example of using your plugin  or even including it in the default scaffold.

Yes, Taiga is public, the project should be accessible without login -> https://tree.taiga.io/project/wojtkowiak-meteor-desktop/us/6?no-milestone=1

**Comment by tzapu** [comment]
thanks
taiga works ;) never worked with it before

if you are ok with it, i would like to add you as a contributor to the notifications plugin, maybe you need to change apis or something and can t wait on me (especially if it gets recommended)

let me know
alex

**Comment by wojtkowiak** [comment]
> if you are ok with it, i would like to add you as a contributor to the notifications plugin, maybe you need to change apis or something and can t wait on me (especially if it gets recommended)

Sure, I'd be honored 👍
