### ISSUE TITLE
Clipboard not working on production

### ISSUE THREAD

**Issue by gooor** [wojtkowiak/meteor-desktop#73]
I have an issue on OSX El Capitan - when I run `npm run desktop` all looks good. When I do `npm run desktop -- build-installer` all looks almost good beside - CMD+V CMD+C shortcuts are not working at all

**Comment by wojtkowiak** [comment]
Hey, sorry for no reply. Had a hectic week.
I will try to reproduce it tomorrow. At first glance it seems to be related to Electron or electron-builder rather than meteor-desktop but I am not ruling that out.
Could you try to build any standalone electron project with electron-builder as see if that also happens?

**Comment by wojtkowiak** [comment]
Oh my. I have forgot to leave my findings here.
I did reproduce it. In case this is still relevant here is what you need to do to make it work:
https://pracucci.com/atom-electron-enable-copy-and-paste.html
or you can use this https://www.npmjs.com/package/electron-default-menu

**Comment by gooor** [comment]
Ok, I found some time to check that - yup that solve the problem https://pracucci.com/atom-electron-enable-copy-and-paste.html
Thanks you!
