### ISSUE TITLE
Hot code reload doesn't work, causes error when meteor running at not port 80

### ISSUE THREAD

**Issue by andrew-luminal** [wojtkowiak/meteor-desktop#80]
Hey, I'm developing an app which needs to run on a bunch of computers on a LAN that all point to the same meteor server. The address of my server is 192.168.1.146:3000.

I try starting meteor with:
`meteor --mobile-server=192.168.1.146`

and then starting meteor-desktop with
`npm run desktop -- run 192.168.1.146:3000`

(running `npm run desktop`, `npm run desktop -- run 192.168.1.146` don't work at all because they don't find the server which is running at port 3000. Since this is an internal video signage app, I don't need/want to use the public internet port.)

Everything works fine until I do a hot code push -- when I try that, I get this error:
`[autoupdate] download failure: error downloading asset manifest: Error: Invalid protocol: 192.168.1.146:` <-- the colon is the last thing, so it seems to be stripping off the port.

I thought it might be trying to parse the colon as part of the http protocol, so I tried adding that:
`npm run desktop -- run http://192.168.1.146:3000`. This works until a hot reload, which causes a different error: it ignores the port after the reload and tries to just use `http://192.168.1.146`, which doesn't work.

I also tried the `--port 3000` option:
`npm run desktop -- run 192.168.1.146:3000 --port 3000`
...but it ignored the port when looking for the server and never starts up correctly.

Possible I'm going about this all wrong, but not sure what else to try.

**Comment by andrew-luminal** [comment]
An update: Hot code reload does work with this configuration:
`meteor --mobile-server=192.168.1.146`
`npm run desktop` (no args)

However that doesn't work when I package the app using
`npm run desktop -- package`. The app opens initially and works but on hot code reload I get this error:
`[autoupdate] Download failure: Skipping downloading new version because the .desktop compatibility version have changed and is potentially incompatible (13b9d0d7d3cda6f307bbf22b2caa757e != 9c5f013f09b421bf1d31418af21da7e7)`

**Comment by andrew-luminal** [comment]
Was able to resolve that last issue by settings `desktopHCP` to `false`. Closing this issue, though I'm still wondering how to specify a port explicitly using the `DDP_URL` command line argument. Regardless, leaving it blank is working for now. Sorry for the trouble.

**Comment by wojtkowiak** [comment]
Hey,
`--port` is only to specify on which port you are currently running the project (in case you are running `meteor` command with `-p`).

`npm run desktop` will take the ddp url that was provided to `--mobile-server`. 
If you want you can change it - this is the correct format `npm run desktop -- http://192.168.1.146:3000` but this is rather used when you are building with `-b` so that meteor-desktop will run your meteor project.

If you are packaging with `npm run desktop -- package` you are building in production mode by default. 
If you try to push HCP changes to it it will not work that is because compatibility version is different. You need to run `meteor --production` to be able to receive HCP.

Quoting documentation:
> if your run a production build of your desktop app it will not receive updates from project run from meteor command unless you run it with --production - that is because development build has devtron added and therefore the compatibilityVersion is different
