### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#85]
In the Readme it states that a release candidate is planned for June 2017. However I don't see what is still on the roadmap. 

We are currently testing this implementation and will probably start using it in production as of May, as we don't see any blockers. 

Could you share whether there are, to your knowledge, any blockers and/or which issues you would like to see fixed before we can dub this an RC?

**Comment by KoenLav** [comment]
https://tree.taiga.io/project/wojtkowiak-meteor-desktop/kanban

Any specific priority in the issues?

**Comment by wojtkowiak** [comment]
Hey,

when it comes to me I am already using meteor-desktop for two released products from version `0.3.0`. My plan was to release a 1.0 once I will have enough reports from the community that it works well and the functionalities provided are sufficient for them to build desktop apps.

At this moment most of the things I have in the backlog are minor improvements. I still haven't decided yet what I'd like to have ready for 1.0 but the only big topic right now in the plan is ensuring a stable solution for making localStorage work. If I decided to release a 1.0 RC right now this is the only thing I'd like to have fixed.

**Comment by KoenLav** [comment]
Alright! We currently have a reseller testing our Windows app with two customers.

Experimental localStorage is enabled, it seems to work fine. Would you like us to test any specific cases for the experimental localStorage implementation? Do you still see any downsides?

**Comment by wojtkowiak** [comment]
Right now the port on which the internal webserver serves the app is random at every start. That forces the renaming of Chrome's localStorage files each time the app is started or receives HCP. In case the renaming fails (and that can happen on Windows when anitviruses etc are accessing the files) - previously set localStorage gets lost. 
In general it works and we are using it but is not bulletproof and your app needs to be ready for this possibility.

What I have in plan is that every meteor-desktop app installed on the machine will reserve one port and always use it. A globally available file will be placed somewhere with this. If the port will not be available at the app start, only then the files will have to be renamed but I will make that not to fail silently as it is right now.

**Comment by KoenLav** [comment]
Seems like a solid plan.

A little MVP thinking: why save the port in a global location? A great first start would be saving the port in the application data directory and using it every time the application starts (rather unlikely there will be a collision this way).

Something like this could probably be implemented with minimal effort (or am I missing something).

**Comment by KoenLav** [comment]
The current experimental localStorage implementation, for our test clients, appears to work just fine!

**Comment by wojtkowiak** [comment]
> A great first start would be saving the port in the application data directory and using it every time the application starts (rather unlikely there will be a collision this way).

Yeah, you are very right in this and that is actually the course I have taken. New mechanism for that is ready in 80%. 
I still have to decide what to do in the worst scenario when the app starts, port is used so the app chooses another one but fails to migrate the localStorage files (the renaming of the files fails). This is very very unlikely to happen but still I need to have this covered. I wanted the app to fail to start but on the other hand localStorage is the kind of storage that your app should be prepared to loose. 

What is your opinion? Or what would you expect as the developer? I can always add an option to settings.json but at least I must decide what will be the default behavior.

**Comment by KoenLav** [comment]
To further decrease the likelihood of this ever occurring I guess you could try migrating the files 3 times (with a certain time interval).

If that doesn't work, as a developer, I would expect the application to simply start with an empty localStorage.

I think also for users this is acceptable; how many times did you open an app on your smartphone and, for some reason, you were logged out. This kind of stuff happens.

For us specifically; we store a unique device identifier in the localStorage, to identify the device between sessions. I'd prefer it never to get lost, but in the case it does the user is simply asked to register a new device ID (which will need to be confirmed before the device can be used).

**Comment by sferoze** [comment]
@wojtkowiak I like this plan for localStorage. Currently the offline data store is one of the biggest issues in meteor-desktop. After first using meteor-desktop it took me awhile to discover a solution to the localStorage issue.... (I should have just searched the issue sooner though). The issues thread regarding localStorage helped me solve this issue. 

If we reuse the same port, then that will not only solve the issue for localStorage, but also for things like IndexedDB and WebSQL. Currently I have to force the desktop app to use localStorage instead of IndexedDB since meteor-desktop only supports localStorage using the `experimentalLocalStorage: true` settings. But IndexedDB is preferred since it is faster. 

So reusing the same port is something I am looking forward too! 

Also in the case that the port is used and it cannot rename the storage files, it should just load the app with empty localStorage. But, it would be great if the desktop app emitted an event in this scenario. Then the developer can do whatever they want if this scenario ever occurs.

**Comment by wojtkowiak** [comment]
Support for IndexedDB will come in 1.0 (currently working on a RC)

> Also in the case that the port is used and it cannot rename the storage files, it should just load the app with empty localStorage. But, it would be great if the desktop app emitted an event in this scenario. Then the developer can do whatever they want if this scenario ever occurs.

Yes, there will be event for that 👍

**Comment by Ajaay** [comment]
Hi @wojtkowiak,

Has there been any progress on the IndexedDB support front?

I currently upload blob data to S3 but very rarely that upload is failing and I need a way of temporarily storing blobs to prevent data loss. This wouldn't need to be persistent between app restarts.

Is this possible at all on the current version or would it need the support mentioned into your comment above?

Thanks!

**Comment by Ajaay** [comment]
Hi @wojtkowiak .

Ok so as I understand it, the issue with Local Storage is simply down to the port number changing each time the app is relaunched, and therefore the file name of the local storage? Is the issue with IndexedDB you're hoping to fix the same or something else entirely?

If it is, I'm not sure it'll be a problem for me as I don't need the data to persist between app relaunches and will delete the table after I'm done with it. 

Now I've tried dropping in a rough implementation using dexie.js but I'm having problems, only with blob storage it would seem...

I can create tables and add indexes but for some reason a blob does not get added. No error, just an empty field. If I run it directly in the chrome browser it works fine. So I'm trying to figure out if it's a Meteor Desktop thing, or an Electron thing. It's odd that basic strings get saved ok, but not the blob data...

I know you're struggling to find time for the project at the moment and I'd be happy to help out with whatever it was you were planning for IndexedDB support...

Thanks!

**Comment by Ajaay** [comment]
OK seems this was an issue with Dev Tools...The blob data was actually being stored.

Whether that's specific to Meteor-desktop or electron in general I don't know.

Next on my list is to figure out how to delete the files when I'm done but I don't think that will be too difficult.

**Comment by Ajaay** [comment]
Ok so some more progress on this. I have taken the localStorage internal module and rewritten it as a custom module to do pretty much the same thing for indexedDB as well. That handles the renaming of folders to match the new port we're running on. BUT and it's a bit but for me right now.

I'm using indexedDB to save blob data acting purely as a client cache, before uploading it off to AWS. Following a successful upload, I delete the record from indexedDB. 

The problem is that following the successful delete from indexedDB, the storage file still persists in the Indexed DB folder, which for my use case could get into the GB's. 

I've tested directly in Chrome and garbage collection takes care of removing the blob data seconds after the record deletion, but this doesn't happen in desktop.

To get around this I could submit an IPC request to kickoff the file delete manually, but Chrome assigns a random filename to the blob, which I've not found a way of influencing yet.

@wojtkowiak - Do you have any ideas on why this might be?

This and the devtools issue might be linked.

What's strange is that I can perform a search on the database and retrieve the blob data, which is why I can successfully perform my uploads.
