### ISSUE TITLE
NSIS vs Squirrel.Windows

### ISSUE THREAD

**Issue by KoenLav** [wojtkowiak/meteor-desktop#86]
Why do the default settings make use of squirrel.windows rather than NSIS.

Are there any specific reasons for making this decision?

**Comment by wojtkowiak** [comment]
No, not really. The decision was based on the fact that Atom is using it. It did fit for my projects so that is why the default config is only for squirrel. Right now I would probably suggest to use NSIS but did not have enough time to check it. I will however migrate one of my products to it as I need a machine wide install which is something you can not get from squirrel (at least afaik).

**Comment by KoenLav** [comment]
It seems the Electron community is moving away from Squirrel in favor of NSIS.

Great to hear you're already planning to migrate one app. I already created a NSIS build for our app and it didn't seem to cause any problems.

Are there any specific pitfalls we should be on the lookout for?

**Comment by wojtkowiak** [comment]
Yeah, I know. When I was starting this a year ago Squirrel was favored. 

> Are there any specific pitfalls we should be on the lookout for?

Not that I know of. In fact I have just build a NSIS machine wide installer and it works great 🙂

**Comment by KoenLav** [comment]
Great! In that case we will keep making use of NSIS and report any issues should they arise.
